Hamburgercim/Areas/Admin/Controllers/DashboardController.cs
using Hamburgercim.Models.Data.Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Hamburgercim.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        private readonly UygulamaDbContext _db;

        public DashboardController(UygulamaDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var siparislerListesi = _db.Siparisler.Include(o => o.Hamburger).Include(o => o.Icecek).Include(o => o.Boyut).Include(o => o.EkstraMalzeme).OrderByDescending(s => s).ToList();
            return View(siparislerListesi);
        }
    }
}

Hamburgercim/Controllers/HomeController.cs
using Hamburgercim.Models;
using Hamburgercim.Models.Data.Classes;
using Hamburgercim.Models.Data.Context;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Hamburgercim.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly UygulamaDbContext _db;

        public HomeController(ILogger<HomeController> logger, UygulamaDbContext db)
        {
            _logger = logger;
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Hamburgercim/Controllers/SiparisController.cs
using Hamburgercim.Models.Data.Classes;
using Hamburgercim.Models.Data.Context;
using Hamburgercim.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Hamburgercim.Controllers
{
    public class SiparisController : Controller
    {
        private readonly UygulamaDbContext _db;

        public SiparisController(UygulamaDbContext db)  // db bir kere newlenir
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var model = new IndexViewModel();
            model.HamburgerList = _db.Hamburgerler.ToList();
            model.IcecekList = _db.Icecekler.ToList();
            model.Ekstralar = _db.EkstraMalzemeler.Select(e => new SelectListItem()
            {
                Text = e.EkstraMalzemeAd + "-" + e.EkstraMalzemeFiyat,
                Value = e.EkstraMalzemeId.ToString(),
            }).ToList();
            model.BoyutList = _db.Boyutlar.ToList();
            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Index(IndexViewModel vm)
        {
            Siparis siparis = new Siparis();
            List<EkstraMalzeme> ekstraList = new List<EkstraMalzeme>();
            var secilenHamburger = _db.Hamburgerler.Where(m => m.HamburgerId == vm.Siparis.Hamburger.HamburgerId).FirstOrDefault();
            var secilenIcecek = _db.Icecekler.Where(m => m.IcecekId == vm.Siparis.Icecek.IcecekId).FirstOrDefault();
            foreach (var item in vm.Ekstralar)
            {
                if (item.Selected)
                {
                    ekstraList.Add(_db.EkstraMalzemeler.FirstOrDefault(e => e.EkstraMalzemeId == Convert.ToInt32(item.Value)));
                }
            }
            siparis.SiparisAdet = vm.HamburgerAdet;
            siparis.Hamburger = secilenHamburger;
            siparis.EkstraMalzeme = ekstraList;
            siparis.Boyut = _db.Boyutlar.Find(vm.BoyutId);
            siparis.Icecek = secilenIcecek;
            siparis.Hamburger.HamburgerFoto = secilenHamburger.HamburgerFoto;
            siparis.ToplamTutar = (siparis.Hamburger.HamburgerFiyat + siparis.Boyut.BoyutFiyat + siparis.Icecek.IcecekFiyat) * siparis.SiparisAdet;
            siparis.ToplamTutar += ekstraList.Sum(e => e.EkstraMalzemeFiyat);
            _db.Siparisler.Add(siparis);
            _db.SaveChanges();
            return RedirectToAction("SiparisGoster");
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult SiparisEkle(Siparis siparis)
        {
            return View();
        }

        public IActionResult SiparisGoster()
        {
            var lastOrder = _db.Siparisler
    .Include(o => o.Hamburger)
    .Include(o => o.Icecek)
    .Include(o => o.Boyut)
    .Include(o => o.EkstraMalzeme)
    .OrderByDescending(o => o.SiparisId)
    .FirstOrDefault();
            return View(lastOrder);
        }
    }
}

Hamburgercim/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<html>
<body>



    <header>

        <a href="#home" class="logo"><i class="fas fa-utensils"></i>HamBurgercim</a>

        <div id="menu-bar" class="fas fa-bars"></div>

        <nav class="navbar">
            <a href="#home">Anasayfa</a>
            <a href="#speciality">Spesiyallerimiz</a>
            <a href="#review">Yorumlar</a>
            <a asp-controller="Siparis" asp-action="Index">Sipariş Ver</a>
            <a asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Admin</a>
        </nav>

    </header>


    <section class="home" id="home" >

        <div class="content">
            <h3>Lezzet Seni Çağırıyor!!!</h3>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptas accusamus tempore temporibus rem amet laudantium animi optio voluptatum. Natus obcaecati unde porro nostrum ipsam itaque impedit incidunt rem quisquam eos!</p>
            <a asp-controller="Siparis" asp-action="Index" class="btn">Sipariş Ver</a>
        </div>

        <div class="image">
            <img src="~/images/home-img.png" alt="">
        </div>

    </section>


    <section class="speciality" id="speciality">

        <h1 class="heading"> our <span>speciality</span> </h1>

        <div class="box-container">

            <div class="box">
                <img class="image" src="~/images/s-img-1.jpg" alt="">
                <div class="content">
                    <img src="~/images/s-1.png" alt="">
                    <h3>tasty burger</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda inventore neque amet ipsa tenetur voluptates aperiam tempore libero labore aut.</p>
                </div>
            </div>
            <div class="box">
                <img class="image" src="~/images/s-img-2.jpg" alt="">
                <div class="content">
                    <img src="~/images/s-2.png" alt="">
                    <h3>tasty pizza</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda inventore neque amet ipsa tenetur voluptates aperiam tempore libero labore aut.</p>
                </div>
            </div>
            <div class="box">
                <img class="image" src="~/images/s-img-3.jpg" alt="">
                <div class="content">
                    <img src="~/images/s-3.png" alt="">
                    <h3>cold ice-cream</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda inventore neque amet ipsa tenetur voluptates aperiam tempore libero labore aut.</p>
                </div>
            </div>
            <div class="box">
                <img class="image" src="~/images/s-img-4.jpg" alt="">
                <div class="content">
                    <img src="~/images/s-4.png" alt="">
                    <h3>cold drinks</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda inventore neque amet ipsa tenetur voluptates aperiam tempore libero labore aut.</p>
                </div>
            </div>
        </div>

    </section>



   

    <div class="step-container">

        <h1 class="heading">how it <span>works</span></h1>

        <section class="steps">

            <div class="box">
                <img src="~/images/step-1.jpg" alt="">
                <h3>choose your favorite food</h3>
            </div>
            <div class="box">
                <img src="~/images/step-2.jpg" alt="">
                <h3>free and fast delivery</h3>
            </div>
            <div class="box">
                <img src="~/images/step-3.jpg" alt="">
                <h3>easy payments methods</h3>
            </div>
            <div class="box">
                <img src="~/images/step-4.jpg" alt="">
                <h3>and finally, enjoy your food</h3>
            </div>

        </section>

    </div>



    <section class="review" id="review">

        <h1 class="heading"> our customers <span>reviews</span> </h1>

        <div class="box-container">

            <div class="box">
                <img src="~/images/pic1.png" alt="">
                <h3>john deo</h3>
                <div class="stars">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="far fa-star"></i>
                </div>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti delectus, ducimus facere quod ratione vel laboriosam? Est, maxime rem. Itaque.</p>
            </div>
            <div class="box">
                <img src="~/images/pic2.png" alt="">
                <h3>john deo</h3>
                <div class="stars">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="far fa-star"></i>
                </div>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti delectus, ducimus facere quod ratione vel laboriosam? Est, maxime rem. Itaque.</p>
            </div>
            <div class="box">
                <img src="~/images/pic3.png" alt="">
                <h3>john deo</h3>
                <div class="stars">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="far fa-star"></i>
                </div>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti delectus, ducimus facere quod ratione vel laboriosam? Est, maxime rem. Itaque.</p>
            </div>

        </div>

    </section>



    

    <!-- scroll top button  -->
    <a href="#home" class="fas fa-angle-up" id="scroll-top"></a>

    <!-- loader  -->
    <div class="loader-container">
        <img src="~/images/burger.gif" alt="">
    </div>
    
</body>
</html>