Hamburgercim/Areas/Admin/Controllers/BoyutController.cs
using Hamburgercim.Models.Data.Classes;
using Hamburgercim.Models.Data.Context;
using Microsoft.AspNetCore.Mvc;

namespace Hamburgercim.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BoyutController : Controller
    {
        private readonly UygulamaDbContext _db;

        public BoyutController(UygulamaDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var boyutlarListesi = _db.Boyutlar.ToList();
            return View(boyutlarListesi);
        }

        public IActionResult Ekle()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Ekle(Boyut boyut)
        {
            if (ModelState.IsValid)
            {
                _db.Boyutlar.Add(boyut);
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public IActionResult Guncelle(int id)
        {
            var guncellenecekBoyut = _db.Boyutlar.Find(id);
            TempData["Id"] = guncellenecekBoyut!.BoyutId;
            return View(guncellenecekBoyut);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Guncelle(Boyut boyut)
        {
            var guncellenecekBoyut = _db.Boyutlar.Find(TempData["Id"]);
            if (ModelState.IsValid)
            {
                guncellenecekBoyut!.BoyutAd = boyut.BoyutAd;
                guncellenecekBoyut.BoyutFiyat = boyut.BoyutFiyat;
                _db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(boyut);
        }

        public IActionResult Sil(int id)
        {
            var silinecekBoyut = _db.Boyutlar.Find(id);
            _db.Boyutlar.Remove(silinecekBoyut!);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Hamburgercim/Areas/Admin/Controllers/DashboardController.cs
using Hamburgercim.Models.Data.Context;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Hamburgercim.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        private readonly UygulamaDbContext _db;

        public DashboardController(UygulamaDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var siparislerListesi = _db.Siparisler.Include(o => o.Hamburger).Include(o => o.Icecek).Include(o => o.Boyut).Include(o => o.EkstraMalzeme).OrderByDescending(s => s).ToList();
            return View(siparislerListesi);
        }
    }
}

Hamburgercim/Areas/Admin/Controllers/HamburgerController.cs
using Hamburgercim.Models.Data.Classes;
using Hamburgercim.Models.Data.Context;
using Hamburgercim.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Hamburgercim.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HamburgerController : Controller
    {
        private readonly UygulamaDbContext _db;
        private readonly Hamburger _hamburger;

        public HamburgerController(UygulamaDbContext db, Hamburger hamburger)
        {
            _db = db;
            _hamburger = hamburger;
        }

        public IActionResult Index()
        {
            var hamburgerListele = _db.Hamburgerler.ToList();

            return View(hamburgerListele);
        }

        public IActionResult Ekle()
        {
            return View();
        }

        [HttpPost,ValidateAntiForgeryToken]
        public IActionResult Ekle(HamburgerViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            if (vm.HamburgerFiyat<= 0)
            {
                return View();
            }


            if (vm.HamburgerResim != null)
            {
                //Önce resmin uzantısını çekelim
                //var uzanti = Path.GetExtension(hamburgerViewModel.HamburgerResmi.FileName);

                //Daha sonra dosyamızın adını oluşturalım 
                var dosyaAdi = vm.HamburgerResim.FileName;

                //Sonra dosyanın kaydedileceği konum belirlenir
                var konum = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", dosyaAdi);

                //Sonra dosya için bir akış ortamı oluşturulur. Kaydetmek için ortam hazırlıyoruz.
                var akisOrtami = new FileStream(konum, FileMode.Create);

                //Resmi o klasöre kaydet 
                vm.HamburgerResim.CopyTo(akisOrtami);
                akisOrtami.Close();

                //Resmi o klasöre kaydettiniz
                //_db'ye de sadece dosya adını ekle
                _hamburger.HamburgerFoto = dosyaAdi;
            }

            _hamburger.HamburgerAd = vm.HamburgerAd;
            _hamburger.HamburgerFiyat = vm.HamburgerFiyat;

            if (_db.Hamburgerler.FirstOrDefault(h => h.HamburgerAd == _hamburger.HamburgerAd) != null)
            {
                return View();
            }

            _db.Hamburgerler.Add(_hamburger);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult Guncelle(int id)
        {
            var guncellenecekHamburger = _db.Hamburgerler.Find(id);
            HamburgerViewModel viewModel = new HamburgerViewModel();
            viewModel.HamburgerAd = guncellenecekHamburger.HamburgerAd;
            viewModel.HamburgerFiyat = guncellenecekHamburger.HamburgerFiyat;
            TempData["Id"] = guncellenecekHamburger.HamburgerId;

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Guncelle(HamburgerViewModel viewModel)
        {
            var guncellenecekHamburger = _db.Hamburgerler.Find((int)TempData["Id"]!);

            if (viewModel.HamburgerResim != null)
            {
                var dosyaAdi = viewModel.HamburgerResim.FileName;
                if (guncellenecekHamburger!.HamburgerFoto == dosyaAdi)
                {
                    return RedirectToAction(nameof(Index));
                }

                //Sonra dosyanın kaydedileceği konum belirlenir
                var konum = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", dosyaAdi);

                //Sonra dosya için bir akış ortamı oluşturulur. Kaydetmek için ortam hazırlıyoruz.
                var akisOrtami = new FileStream(konum, FileMode.Create);

                //Resmi o klasöre kaydet 
                viewModel.HamburgerResim.CopyTo(akisOrtami);
                akisOrtami.Close();

                //Resmi o klasöre kaydettiniz
                //_db'ye de sadece dosya adını ekle
                guncellenecekHamburger.HamburgerFoto = dosyaAdi;
            }

            guncellenecekHamburger!.HamburgerAd = viewModel.HamburgerAd;
            guncellenecekHamburger.HamburgerFiyat = viewModel.HamburgerFiyat;

            var digerHamburgerler = _db.Hamburgerler.Except(_db.Hamburgerler.Where(u => u.HamburgerId == guncellenecekHamburger.HamburgerId)).ToList();

            if (digerHamburgerler.Any(u => u.HamburgerAd == guncellenecekHamburger.HamburgerAd))
            {
                return RedirectToAction(nameof(Index));
            }
            _db.Hamburgerler.Update(guncellenecekHamburger);
            _db.SaveChanges();



            return RedirectToAction(nameof(Index));
        }

        public IActionResult Sil(int id)
        {
            var silinecekHamburger = _db.Hamburgerler.Find(id);

            if (silinecekHamburger == null)
            {
                return View();
            }

            _db.Hamburgerler.Remove(silinecekHamburger);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Resimkaldir(int id)
        {
            var resmiSilinecekHamburger = _db.Hamburgerler.Find(id)!;
            if (resmiSilinecekHamburger.HamburgerFoto == null)
            {
                return RedirectToAction(nameof(Index));
            }
            var resimAdi = resmiSilinecekHamburger.HamburgerFoto;
            resmiSilinecekHamburger.HamburgerFoto = null;
            _db.Hamburgerler.Update(resmiSilinecekHamburger);
            _db.SaveChanges();

            //Bu resmi kullanan başka hamburger yoksa resmi de sil.
            var silinecekHamburgerlerHaricindekiHamburgerler = _db.Hamburgerler.Except(_db.Hamburgerler.Where(u => u.HamburgerId == resmiSilinecekHamburger.HamburgerId));
            var resmiKullananBaskaYok = silinecekHamburgerlerHaricindekiHamburgerler.All(u => u.HamburgerFoto != resimAdi);

            if (resmiKullananBaskaYok)
            {
                //resimler klasörünün olduğu yerdeki dosyaları al.
                string[] dosyalar = Directory.GetFiles("D:\\ÇALIŞMALAR\\Hamburgercim\\Hamburgercim\\wwwroot\\images");
            

                //Bu dosyalardan silmek istediğimizi bulup sileceğiz.
                foreach (var item in dosyalar)
                {
                    var resimIsmiDizisi = item.Split("\\");

                    //Artık dosya adı bu resim dizisinin son elemanı oldu
                    if (resimIsmiDizisi[resimIsmiDizisi.Length - 1] == resimAdi)
                    {
                        System.IO.File.Delete(item);
                        break;
                    }
                }
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Hamburgercim/Areas/Admin/Controllers/IcecekController.cs
using Hamburgercim.Models.Data.Classes;
using Hamburgercim.Models.Data.Context;
using Microsoft.AspNetCore.Mvc;
using System.Security.Cryptography.Xml;

namespace Hamburgercim.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class IcecekController : Controller
    {
        private readonly UygulamaDbContext _db;

        public IcecekController(UygulamaDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var icecekListesi = _db.Icecekler.ToList();
            return View(icecekListesi);
        }

        public IActionResult Ekle()
        {
            return View();

        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Ekle(Icecek icecek)
        {
            if (ModelState.IsValid)
            {
                _db.Icecekler.Add(icecek);
                _db.SaveChanges();
                return RedirectToAction("Index");

            }

            return View();

        }

        public IActionResult Guncelle(int id)
        {
            var guncellenecekIcecek = _db.Icecekler.Find(id);
            TempData["Id"] = guncellenecekIcecek.IcecekId;

            return View(guncellenecekIcecek);
        }

        [HttpPost,ValidateAntiForgeryToken]
        public IActionResult Guncelle(Icecek icecek)
        {
            var guncellenecekıcecek = _db.Icecekler.Find((int)TempData["Id"]!);

            if (ModelState.IsValid)
            {
                guncellenecekıcecek.IcecekAd = icecek.IcecekAd;
                guncellenecekıcecek.IcecekFiyat = icecek.IcecekFiyat;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(icecek);

        }

        public IActionResult Sil(int id)
        {
            var silinecekIcecek = _db.Icecekler.Find(id);
            _db.Icecekler.Remove(silinecekIcecek!);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

Hamburgercim/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>HamBurgercim Admin Paneli - @ViewData["Title"]</title>
    <link href="https://cdn.datatables.net/1.13.1/css/dataTables.bootstrap5.min.css" rel="stylesheet" />
    <link href="~/admin/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <link href="~/admin/lib/summernote/summernote-lite.min.css" rel="stylesheet" />
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Admin Paneli</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
   
        
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <a class="nav-link" asp-controller="Dashboard" asp-action="Index">
                            <div class="sb-nav-link-icon">@*<i class="fas fa-tachometer-alt"></i>*@<i class="fa-solid fa-list"></i></div>
                            Sipariş Listesi
                        </a>
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-external-link"></i></div>
                            Siteye Git
                        </a>
                        <div class="sb-sidenav-menu-heading">Menu Ekle</div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseHamburgerler" aria-expanded="false" aria-controls="collapseHamburgerler">
                            <div class="sb-nav-link-icon">@*<i class="fas fa-columns"></i>*@<i class="fa-solid fa-burger"></i></div>
                            Hamburger
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseHamburgerler" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-area="Admin" asp-controller="Hamburger" asp-action="Ekle">Hamburger Ekle</a>
                                <a class="nav-link" asp-area="Admin" asp-controller="Hamburger" asp-action="Index">Hamburger Listele</a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseIcecekler" aria-expanded="false" aria-controls="collapseIcecekler">
                            <div class="sb-nav-link-icon">@*<i class="fas fa-columns"></i>*@<i class="fa-solid fa-wine-bottle"></i></div>
                            İçecek
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseIcecekler" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-controller="Icecek" asp-action="Ekle">İçecek Ekle</a>
                                <a class="nav-link" asp-controller="Icecek" asp-action="Index">İçecek Listele</a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseEkstramalzemeler" aria-expanded="false" aria-controls="collapseEkstramalzemeler">
                            <div class="sb-nav-link-icon">@*<i class="fas fa-columns"></i>*@<i class="fa-solid fa-coins"></i></div>
                            Ekstra Malzeme
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseEkstramalzemeler" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-controller="Ekstramalzeme" asp-action="Ekle">Ekstra Malzeme Ekle</a>
                                <a class="nav-link" asp-controller="Ekstramalzeme" asp-action="Index">Ekstra Malzeme Listele</a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseBoyutlar" aria-expanded="false" aria-controls="collapseBoyutlar">
                            <div class="sb-nav-link-icon">@*<i class="fas fa-columns"></i>*@<i class="fa-solid fa-ruler"></i></div>
                            Boyut
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseBoyutlar" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-controller="Boyut" asp-action="Ekle">Boyut Ekle</a>
                                <a class="nav-link" asp-controller="Boyut" asp-action="Index">Boyut Listele</a>
                            </nav>
                        </div>

                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Giriş yapıldı:</div>
                    Admin
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    @if (ViewData["Title"] != null)
                    {
                        <h1 class="mt-4">@ViewData["Title"]</h1>
                    }
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Düşler Dünyası @DateTime.Now.Year</div>
                        <div>
                            <a href="#">Gizlilik Politikası</a>
                            &middot;
                            <a href="#">Şartlar &amp; Koşullar</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.3.min.js" integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>
    <script src="~/admin/lib/summernote/summernote-lite.min.js"></script>
    <script src="~/admin/js/scripts.js"></script>
    @await RenderSectionAsync("Scripts", false)
</body>
</html>